name: scvelo

channels:
  - bioconda
  - defaults
  - conda-forge
  - anaconda

dependencies:
  - python=3.8.5
  - scvelo
  - numba=0.52.0
  - notebook
  - ipywidgets
  - python-igraph
  - cellrank=1.5.1
  - openmpi
  - petsc
  - petsc4py
  - slepc
  - slepc4py
  - mpi4py