name: scvelo

channels:
  - bioconda
  - defaults
  - conda-forge
  - anaconda

dependencies:
  - python=3.8.5
  - pip
  - scvelo
  - numba=0.52.0
  - notebook
  - ipywidgets
  - python-igraph
  - openmpi
  - pip:
    - cellrank
    - mpi4py
    - petsc
    - petsc4py
    - slepc
    - slepc4py