name: scvelo

channels:
  - bioconda
  - defaults
  - conda-forge

dependencies:
  - python=3.8.5
  - scvelo
  - numba=0.52.0
  - notebook
  - ipywidgets
  - python-igraph
  -   pip:
    -   cellrank>=1.4.0
    -   louvain>=0.6,!=0.6.2
    -   git+https://github.com/broadinstitute/wot@master