name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches: 
      - master
    paths: 
      - '**/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        tag: ["base"]
        docker-file: ["Dockerfile"]
        module-name: ["palantir", "schelper", "schelper_shiny", "phate", "scvelo", "scatterplot3d", "monocle3"]

    steps:
      - uses: actions/checkout@v2
      - name: Set version and tags
        id: ver
        run: |
          VERSION=`cat NF-downstream_analysis/containers/${{matrix.module-name}}/VERSION`
          echo "version: $VERSION"
          echo "::set-output name=version::$(echo $VERSION)"
        shell: bash
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/10x-npb-${{matrix.module-name}}
          path: NF-downstream_analysis/containers/${{matrix.module-name}}
          dockerfile: NF-downstream_analysis/containers/${{matrix.module-name}}/${{matrix.docker-file}}
          tags: latest,${{matrix.tag}}-${{steps.ver.outputs.version}}
