name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches: [master]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["base"]
        docker-file: ["Dockerfile"]
        module-name: ["seurat_r-3.6.3", "seurat_r-4.0.0", "seurat_r-4.0.3"]

    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/10x-npb-${{matrix.module-name}}
          path: NF-downstream_analysis/containers/${{matrix.module-name}}
          dockerfile: NF-downstream_analysis/containers/${{matrix.module-name}}/${{matrix.docker-file}}
          tags: latest
